apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.deployment.name }}
  name: {{ .Values.deployment.name }}
spec:
  ports:
    - name: 8000-tcp
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: {{ .Values.deployment.name }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
