apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.deployment.name }}
  name: {{ .Values.deployment.name }}
spec:
  ports:
    - name: 3007-tcp
      port: 3007
      protocol: TCP
      targetPort: 3007
    - name: 3001-tcp
      port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: {{ .Values.deployment.name }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
