apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.deployment.name }}
  name: {{ .Values.deployment.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  replicas: {{ .Values.deployment.replica }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - env:
            - name: TZ
              value: {{ .Values.containers.nextjsapp.env.timezone }}
            - name: NEXT_PUBLIC_MAINTENANCE_USERNAME
              value: {{ .Values.containers.nextjsapp.env.muser }}
            # - name: valbaseapi
            #   value: {{ .Values.containers.nextjsapp.env.valbaseapi }}
          image: {{ .Values.containers.nextjsapp.image.repository }}/{{ .Values.containers.nextjsapp.image.name }}:{{ .Values.containers.nextjsapp.image.tag }}
          imagePullPolicy: {{ .Values.containers.nextjsapp.image.pullPolicy }}
          name: {{ .Values.deployment.name }}
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.containers.nextjsapp.resourceLimits.cpu }}
              memory: {{ .Values.containers.nextjsapp.resourceLimits.memory }}
            requests:
              cpu: {{ .Values.containers.nextjsapp.resourceRequests.cpu }}
              memory: {{ .Values.containers.nextjsapp.resourceRequests.memory }}
          volumeMounts:
            - mountPath: appl/cicd/products/{{ .Values.deployment.name }}/properties
              name: {{ .Values.deployment.name }}-configmap
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: prod-registry
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: {{ .Values.deployment.terminationGracePeriodSeconds }}
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ .Values.deployment.name }}-configmap
          name: {{ .Values.deployment.name }}-configmap
