# Default values for chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#NB: We need to quote the yes and no else helm will change it to true and false

deployment:
  name: ""
  replica: 1
  terminationGracePeriodSeconds: 30

route:
  annotations:
    haproxy.router.openshift.io/balance: "roundrobin"
    haproxy.router.openshift.io/disable_cookies: 'true'
    haproxy.router.openshift.io/timeout: "30s"
    openshift.io/host.generated: 'true'

secret:
  labels:
    app: "nodejssecrets"
  data:
    dbURL: ""
    encryptionKey: ""
    jwtSecretKey: ""
    keycloakClientID: ""
    keycloakUsername: ""
    keycloakPassword: ""
    keycloakClientUID: ""
    keycloakAdminRoleId: ""
    keycloakStandardRoleId: ""
    keycloakMemberRoleId: ""
    sparkRootCert: ""
    adoPatToken: ""
    ocp4Url: ""
    ocp4AgentUrl: ""
    ocp4Token: ""
    ocpUser: ""
    ocpUserPassword: ""
    serviceUser: ""

containers:
  repository: "devops-container-registry.artifacts.internal.spark.co.nz"
  nodejsapp:
    env:
      timezone: "Pacific/Auckland"
      ENVIRONMENT: ""
    image:
      project: "cicdapp"
      name: ""
      pullPolicy: "Always"
      tag: ""
    resourceLimits:
      cpu: "600m"
      memory: "600Mi"
    resourceRequests:
      cpu: "200m"
      memory: "600Mi"